version: "3"

services:
  pinger-1:
    image: torrefatto/grpcprobe
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 1
      NAME: pinger-1
      PEERS: pinger-2
    ports:
      - "9091:9090"

  pinger-2:
    image: torrefatto/grpcprobe
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 1
      NAME: pinger-2
      PEERS: pinger-3
    ports:
      - "9092:9090"

  pinger-3:
    image: torrefatto/grpcprobe
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 1
      NAME: pinger-3
      PEERS: pinger-1
    ports:
      - "9093:9090"

  prometheus:
    image: prom/prometheus
    volumes:
      - "./dev/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
