---
global:
  scrape_interval: 5s
  scrape_timeout: 1s

scrape_configs:
  - job_name: pinger
    static_configs:
      - targets:
          - pinger-1:9090
          - pinger-2:9090
          - pinger-3:9090

